### ISSUE TITLE
ClassNotFoundException using leiningen 2.6.0

### ISSUE THREAD

**Issue by dpassen1** [jonase/eastwood#189]
```
Caused by: java.lang.ClassNotFoundException: leiningen.core.project$reduce_dep_step
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at clojure.lang.DynamicClassLoader.findClass(DynamicClassLoader.java:69)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at clojure.lang.DynamicClassLoader.loadClass(DynamicClassLoader.java:77)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:270)
	at clojure.lang.RT.classForName(RT.java:2168)
	at clojure.lang.RT.classForName(RT.java:2177)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1120)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1104)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:792)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1104)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:800)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$EvalReader.invoke(LispReader.java:1104)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:691)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:792)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.Compiler.load(Compiler.java:7374)
```

**Comment by jafingerhut** [comment]
As far as I can tell, this looks very similar to this Leiningen issue, which affects not only Eastwood but many other Leiningen plugins as well: https://github.com/technomancy/leiningen/issues/2079

Leiningen 2.6.1 has been released to fix this, and in my brief testing, I can both reproduce the issue above with Leiningen 2.6.0, and I do not see the issue with Leiningen 2.6.1.  Please try upgrading to Leiningen 2.6.1 and let me know if that fixes the problem for you.

**Comment by dpassen1** [comment]
Can confirm 2.6.1 fixed my issue. Thanks.
