### ISSUE TITLE
Implement warnings disabling for `:unused-fn-args`

### ISSUE THREAD

**Issue by barkanido** [jonase/eastwood#324]
I have this simple `compojure.core` route definition:
```(routes
    (GET "/healthcheck" [] {:status 200 :body "ok"}))
```
which generates:
`endpoint.clj:1:1: unused-fn-args: Function arg request__21327__auto__ never used` wanning

I am trying to disable it in a `clojure.clj` file located in the project root by running:
`lein eastwood "{:linters [:all] :exclude-linters [:implicit-dependencies :keyword-typos :unused-ret-vals :non-clojure-file :no-ns-form-found] :parallelism? :naive :config-files [\"$(pwd)/clojure.clj\"]}"`

my clojure.clj files looks like this:
```
(disable-warning
  {:linter :unused-fn-args
   :if-inside-macroexpansion-of #{'compojure.core/GET}
   :within-depth 1
   :reason "because"})
```

but I get:
```
Unknown error: java.lang.IllegalArgumentException: No matching clause: :unused-fn-args
java.lang.IllegalArgumentException: No matching clause: :unused-fn-args
	at eastwood.util$process_configs$fn__1688.invoke(util.clj:886)
	at clojure.lang.PersistentVector.reduce(PersistentVector.java:341)
	at clojure.core$reduce.invokeStatic(core.clj:6747)
	at clojure.core$reduce.invoke(core.clj:6730)
	at eastwood.util$process_configs.invokeStatic(util.clj:885)
	at eastwood.util$process_configs.invoke(util.clj:884)
	at eastwood.util$init_warning_enable_config.invokeStatic(util.clj:920)
	at eastwood.util$init_warning_enable_config.invoke(util.clj:907)
	at eastwood.lint$last_options_map_adjustments.invokeStatic(lint.clj:470)
	at eastwood.lint$last_options_map_adjustments.invoke(lint.clj:459)
	at eastwood.lint$eastwood.invokeStatic(lint.clj:518)
	at eastwood.lint$eastwood.invoke(lint.clj:507)
	at eastwood.lint$eastwood.invokeStatic(lint.clj:508)
	at eastwood.lint$eastwood.invoke(lint.clj:507)
	at eastwood.lint$eastwood_from_cmdline.invokeStatic(lint.clj:536)
...
```

**Comment by slipset** [comment]
Sorry for the delay.
It seems that `:unused-fn-args` does not allow for configuration. 
A PR which solves this would be welcome.

**Comment by vemv** [comment]
This was implemented in https://github.com/jonase/eastwood/commit/ad0c26c
